### ISSUE TITLE
Add test runs for OpenAI models in `ci.yml`

### ISSUE THREAD

**Issue by drew2a** [drew2a/ai-review#4]
Claude Sonnet 3.5/3.7 turns out to be the first model that can actually be used effectively in `AI Review`, so the `ci.yml` runs it by default.  

However, it would be beneficial to run OpenAI models as well, for testing purposes.

Example of an OpenAI model run:

```yml
name: AI Review
on: [ pull_request ]
permissions:
  pull-requests: write
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          api_endpoint: ${{ secrets.LLM_ENDPOINT }}
          api_key: ${{ secrets.LLM_API_KEY }}
          api_version: ${{ secrets.LLM_API_VERSION }}
          llm_model: ${{ secrets.LLM_MODEL }}

          github_token: ${{ secrets.GITHUB_TOKEN }}

          debug: true
          add_review_resolution: false

```
